version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: db-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user_mysql
      MYSQL_PASSWORD: pass_mysql
    ports:
      - "3306:3306"
    volumes:
      - db-mysql-data:/var/lib/mysql

  mongo:
    image: mongo:latest
    container_name: db-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: user_mongo
      MONGO_INITDB_ROOT_PASSWORD: pass_mongo
    ports:
      - "27017:27017"
    volumes:
      - db-mongo-data:/data/db
      - db-mongo-config:/data/configdb

  postgres:
    image: postgres:latest
    container_name: db-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user_postgres
      POSTGRES_PASSWORD: pass_postgres
    ports:
      - "5432:5432"
    volumes:
      - db-postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: db-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  db-mysql-data:
    driver: local
  db-mongo-data:
    driver: local
  db-mongo-config:
    driver: local
  db-postgres-data:
    driver: local
